name: marketool_financer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  tutorial_coach_mark: ^1.2.2
  file_selector: ^1.0.3
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf
  assets:
    - assets/images/
